### PR TITLE
[uniffi] Rename `commit` to `key_update`

### PR DESCRIPTION
**Pull request by mgeisler**
### Issues:

Addresses #81.

### Description of changes:

When discussing this internally, the feeling was that `commit` would mostly be used to refresh keys. The name `key_update` would thus be more descriptive.

### Call-outs:

Since the method can also be used to commit received proposals (if/when we support them), the current name might be better?

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 and MIT license.

### CODE REVIEW

**Comment by mgeisler** [comment]
> Since the method can also be used to commit received proposals (if/when we support them), the current name might be better?

The changes in the tests show this a bit, but I'll let people here discuss :smile:

**Comment by mulmarta** [comment]
I'm not so sure about this one...
1. This could have 2 purposes: PCS as key_update indicates or committing received proposals
2. Depending on your commit_options and received proposals, this may **NOT** update any keys. E.g. if you received add proposals and your commit_options don't enforce path, then this will end up being a partial commit i.e. it doesn't update any keys

**Comment by beurdouche** [comment]
Without having looked into this much, a side note is that we should avoid non standard terminology as much as possible.

**Comment by mgeisler** [comment]
Thanks for the feedback! Let me close this for now since it doesn't sound like a good idea.

**Pull request closed without merging**
